# Parameters in `system` section define how Panorama interacts with system
# environment, such as the file system or PostgreSQL server
[system]
# Path to the game directory
# Default: "/var/lib/panorama/game"
game_path = "/var/lib/panorama/game"

# Path to the world directory
# Default: "/var/lib/panorama/world"
world_path = "/var/lib/panorama/world"

# DSN string used for connecting to PostgreSQL
# Default: ""
world_dsn = ""

# Path to the tile storage directory
# Default: "/var/lib/panorama/tiles"
tiles_path = "/var/lib/panorama/tiles"

# Parameters in `web` section can be used to tweak the web interface
[web]
# Address to serve the map from
# Default: ":33333"
listen_address = ":33333"

# Web page title
# Default: "Server map"
title = "Server map"

# Parameters in the `renderer` section
[renderer]
# Number of worker threads used for rendering
# Default: 2
workers = 2

# Number of zoom levels
# Default: 8
zoom_levels = 8

# Parameters in the `region` section define what portions of the map Panorama
# renders and shows
[region]
# Cuboid region containing the map, defined by its minimum and maximum
# coordinates, measured in nodes.
x_bounds = { min = -100, max = 100 }
y_bounds = { min = -32, max = 160 }
z_bounds = { min = -100, max = 100 }
